# Generated by Django 4.1.7 on 2023-02-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siz', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prodct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('brand', models.CharField(default='No Brand', max_length=50)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('specification', models.TextField(blank=True, max_length=500, null=True)),
                ('quantite', models.IntegerField()),
                ('img_prdct', models.ImageField(default='no-img.jpg', upload_to='prdct_imges/')),
                ('img_slide1', models.ImageField(upload_to='img_slide/img1')),
                ('img_slide2', models.ImageField(upload_to='img_slide/img2')),
                ('img_slide3', models.ImageField(upload_to='img_slide/img3')),
                ('img_slide4', models.ImageField(upload_to='img_slide/img4')),
                ('color', models.ManyToManyField(to='zayshopUI.color')),
                ('size', models.ManyToManyField(to='zayshopUI.size')),
            ],
        ),
    ]
