# Generated by Django 4.1.7 on 2023-02-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshopUI', '0002_remove_prodct_color_remove_prodct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodct',
            name='img_slide1',
            field=models.ImageField(default='no-img.jpg', upload_to='img_slide/img1'),
        ),
        migrations.AlterField(
            model_name='prodct',
            name='img_slide2',
            field=models.ImageField(default='no-img.jpg', upload_to='img_slide/img2'),
        ),
        migrations.AlterField(
            model_name='prodct',
            name='img_slide3',
            field=models.ImageField(default='no-img.jpg', upload_to='img_slide/img3'),
        ),
        migrations.AlterField(
            model_name='prodct',
            name='img_slide4',
            field=models.ImageField(default='no-img.jpg', upload_to='img_slide/img4'),
        ),
    ]
