# Generated by Django 4.1.7 on 2023-02-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshopUI', '0003_alter_prodct_img_slide1_alter_prodct_img_slide2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodct',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
