# Generated by Django 4.1.7 on 2023-02-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshopUI', '0004_prodct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodct',
            name='color',
            field=models.ManyToManyField(to='zayshopUI.color'),
        ),
        migrations.AddField(
            model_name='prodct',
            name='size',
            field=models.ManyToManyField(to='zayshopUI.size'),
        ),
    ]
