# Generated by Django 4.1.7 on 2023-02-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayshopUI', '0005_prodct_color_prodct_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=50)),
            ],
        ),
    ]
